services:
  app:
    entrypoint:
      - sleep
      - infinity
    image: node:latest
    init: true
    environment:
      - WATCHPACK_POLLING=true;
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    network_mode: host
